# Generated by Django 3.1.2 on 2020-10-19 20:41

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            '''
             CREATE TABLE account(
                id text,
                balance numeric,
                currency text
                );
            ''',
            'drop table account;'
        )
    ]
